#' Exporting results
#' @param paths Character vector of paths to store intput, intermediary results, outputs...
#' @param FCS_export if "none", no FCS export. if "concatenated", export one FCS file with all the data. if "split", export the data in the result folder under the subfolder FCS, with each file corresponding to a (subsampled) input file. If "csv", export raw concatenated data to CSV.
#' @param chans vector of backbone channels' names
#' @param transforms named list of asinh-transformations and reverse transformations
#' @param umap UMAP dimensionality reduction matrix of the Backbone data
#' @param preds matrix of imputed data
#' @param annot annotation table generated by infinityFlow:::initialize()
#' @param verbose Verbosity
#' @importFrom utils read.csv write.csv
#' @importFrom stats setNames
#' @importFrom flowCore inverseLogicleTransform flowFrame write.FCS
#' @noRd

export_data <- function(
                     paths,
                     FCS_export,
                     chans=readRDS(file.path(paths["rds"],"chans.Rds")),
                     transforms=readRDS(file.path(paths["rds"],"transforms.Rds")),
                     umap=readRDS(file.path(paths["rds"],"umap.Rds")),
                     annot=read.csv(paths["annotation"],sep=",",header=TRUE,stringsAsFactors=FALSE),
                     verbose=TRUE,
                     yvar
                     ){
    if(verbose){
        message("Exporting results")
    }
    
    ## annot <- setNames(as.character(annot[,"target",]),annot[,"file"])
        write.csv(
        file = file.path(paths["output"],"Exploratory_Ab_ID_table.csv"),
        data.frame(
            file = annot$file,
            target = annot$target,
            Exploratory_Ab_ID = seq_len(nrow(annot))),
        row.names=FALSE
    )

    umap_ranges <- apply(umap, 2, range)
    
    if(verbose){
        message("\tTransforming predictions back to a linear scale")
    }
    preds_concatenated <- list()
    
    for(i in seq_len(nrow(annot))){
        preds <- h5read(file = paths["h5"], name = paste0("/predictions/raw/", i))
        preds <- transforms[[yvar]]$backward(preds)
        colnames(preds) <- paste0(annot$target, ".XGBoost")
        h5writeAttribute(attr = colnames(preds), h5obj = paths["h5"], name = "colnames", h5loc = paste0("predictions/raw/", i))
        
        index <- list(
                which(h5read(file = paths["h5"], name = paste0("sampling/predictions/", i)) == 1L),
                NULL
        )
        backbone_data <- h5read(file = paths["h5"], name = paste0("/input/expression/", i), index = index)
        colnames(backbone_data) <- h5readAttributes(file = paths["h5"], name = paste0("/input/expression/", i))$colnames

        umap_i <- h5read(file = paths["h5"], name = paste0("/umap/backbone/", i))
        colnames(umap_i) = paste0("UMAP", 1:2)
        for(j in seq_len(ncol(umap_i))){
            umap_i[, j] <- (umap_i[, j] - umap_ranges[1, j])/(umap_ranges[2, j] - umap_ranges[1, j])*10000
        }
        preds <- cbind(
            backbone_data,
            preds,
            Exploratory_Ab_ID = i,
            umap_i
        )
        if("csv" %in% FCS_export){          
            if(verbose & i == 1){
                message("\t","Exporting as a concatenated CSV file")
            }
            write.table(
                preds,
                file = file.path(paths["output"], "results.csv"),
                row.names = FALSE,
                append = i != 1,
                col.names = i == 1,
                sep = ","
            )
        }

        if("split" %in% FCS_export){
            if(verbose & i == 1){
                message("\t","Exporting FCS files (1 per well)")
            }
            dir.create(file.path(paths["output"],"FCS","split"),showWarnings=FALSE,recursive=TRUE)
            FCS <- flowFrame(preds)
            FCS@parameters$desc <- as.character(FCS@parameters$desc)
            FCS@parameters$name <- as.character(FCS@parameters$name)
            FCS <- generate_description(FCS)
            invisible(
                write.FCS(
                    FCS,
                    filename = file.path(paths["output"], "FCS", "split", paste0(sub(".fcs","",annot[i, "file"]), "_target_", gsub("/", "-", annot[i, "target"]), ".fcs"))
                )
            )
        }
        if("concatenated" %in% FCS_export){
            preds_concatenated <- c(preds_concatenated, list(preds))
        }
    }

    if("concatenated" %in% FCS_export){
        if(verbose){
            message("\t","Exporting concatenated FCS file\n\t\t/!\\ Warning /!\\ - this may use a lot of RAM, consider 'split' exports")
        }
        dir.create(file.path(paths["output"], "FCS", "concatenated"), showWarnings = FALSE, recursive = TRUE)
        FCS <- flowFrame(do.call(rbind, preds_concatenated))
        FCS@parameters$desc <- as.character(FCS@parameters$desc)
        FCS@parameters$name <- as.character(FCS@parameters$name)
        FCS <- generate_description(FCS)
        invisible(write.FCS(FCS,filename=file.path(paths["output"],"FCS","concatenated","concatenated_results.fcs")))
    }

    invisible()
}
