#' Plot the UMAP embedding of the backbone with color-coded intensities for backbone and predicted measurements
#' @param paths Character vector of paths to store intput, intermediary results, outputs...
#' @param chop_quantiles removes the top and bottom \emph{chop_quantiles} of the intensity scale for each marker when mapping intensities to colors.
#' @param chans vector of backbone channels' names
#' @param events.code vector of length nrow(xp) specifying from which well each event originates
#' @param preds matrix of imputed data
#' @param sampling boolean vector of length nrow(xp) specifying which events were selected for final imputation
#' @param prediction_colnames vector of column names for the imputed data, a subset of the column names in the preds matrix
#' @param a annotation table generated by infinityFlow:::intialize()
#' @param file_name File name of the output PDF
#' @param global_palette Whether color scaling should be global or specific to each marker
#' @param verbose Verbosity
#' @importFrom stats quantile
#' @importFrom matlab jet.colors
#' @noRd
plot_results <- function(
                      paths,
                      chop_quantiles=0.005,
                      chans=readRDS(file.path(paths["rds"],"chans.Rds")),
                      annot=read.csv(paths["annotation"],sep=",",header=TRUE,stringsAsFactors=FALSE),
                      verbose=TRUE,
                      file_name=file.path(paths["output"],"umap_plot_annotated.pdf"),
                      transforms=readRDS(file.path(paths["rds"], "transforms.Rds")),
                      yvar,                      
                      umap_group = "/umap/backbone/",
                      backbone_data_group = "/input/expression_transformed/",
                      predictions_group = "/predictions/raw/",
                      cores
                      ){
    if(verbose){
        message("Plotting")
    }

    n <- sum(h5read(paths["h5"], name = "/dimensions/", index = list(NULL, 2))) ## Total number of events with predictions

    color_biplot_by_channels(
        paths["h5"],
        annot=annot,
        file_name=file_name,
        palette=jet.colors(100),
        pch=16,
        cex= max(1 - 0.1*(log10(n)), 0.1),
        resolution=72,
        raster.height=360*4,
        raster.width=360*4,
        transforms = transforms,
        chans = chans,
        yvar = yvar,
        ## data_transformation_reverse=transforms[[yvar]]$backward,
        chop_quantiles = chop_quantiles,
        umap_group = umap_group,
        backbone_data_group = backbone_data_group,
        predictions_group = predictions_group,
        cores=cores
    )
}
