#' Generate reports on prediction performance
#' @param paths Character vector of paths to store intput, intermediary results, outputs...
#' @param annot annotation table generated by infinityFlow:::intialize()
#' @param verbose Verbosity
#' @param yvar name of the exploratory measurement parameter
#' @noRd
quality_controls <- function(
                             paths,
                             yvar,
                             annot=read.csv(paths["annotation"],sep=",",header=TRUE,stringsAsFactors=FALSE),
                             verbose=TRUE
                             ){
    if(verbose){
        message("Generating quality controls")
    }
    
    qc_dir <- file.path(paths["output"],"quality_controls")
    dir.create(qc_dir,showWarnings=FALSE,recursive=TRUE)

    performance_across_models <- annot[, c("file", "target")]
    performance_across_models <- cbind(performance_across_models, Rsquared_train_set = NA, Rsquared_test_set = NA)
    
    pdf(file.path(qc_dir, "predictions_performance.pdf"), width = 14, height = 7)
    par(mfrow = c(1, 2), oma = c(0, 0, 3, 0))
    for(i in seq_len(nrow(annot))){
        test_set = h5read(paths["h5"], paste0("/sampling/fitting/", i)) == 0L
        predicted = h5read(paths["h5"], paste0("/predictions/intra_well/", i))
        measured = h5read(paths["h5"], paste0("/input/expression_transformed_scaled/", i))
        colnames(measured) = h5readAttributes(paths["h5"], paste0("/input/expression/", i))$colnames
        measured = measured[, yvar]

        xr = range(measured)
        yr = range(predicted)
        performance_across_models[i, "Rsquared_train_set"] = cor(measured[!test_set], predicted[!test_set])^2
        performance_across_models[i, "Rsquared_test_set"] = cor(measured[test_set], predicted[test_set])^2

        freqplot(measured[!test_set], predicted[!test_set], main = "Train set", xlim = xr, ylim = yr)
        title(xlab = "Measured", ylab = "Predicted")
        abline(a = 0, b = 1, lty = 2)
        legend(x = "bottomright", lty = 2, legend = "y = x", bty = " n")
        legend(x = "topleft", legend = paste0("R-squared = ", signif(performance_across_models[i, "Rsquared_train_set"], 2)), bty = "n")

        freqplot(measured[test_set], predicted[test_set], main = "Test set", xlim = xr, ylim = yr)
        title(xlab = "Measured", ylab = "Predicted")
        abline(a = 0, b = 1, lty = 2)
        legend(x = "bottomright", lty = 2, legend = "y = x", bty = " n")
        legend(x = "topleft", legend = paste0("R-squared = ", signif(performance_across_models[i, "Rsquared_test_set"], 2)), bty = "n")
        
        mtext(side = 3, outer = TRUE, at = 0.5, text = annot[i, "target"])
    }
    dev.off()

    write.csv(performance_across_models, file = file.path(qc_dir, "QC_metrics.csv"), row.names = FALSE)
    invisible()
}
